"""
MantraAI — Evidence & Guideline Retrieval Layer
================================================

PURPOSE
-------
Deterministically retrieves authoritative clinical guideline excerpts and systematic
review summaries matching the `evidence_tags` produced by the Health Domain & Context Engine.

CLINICAL & ETHICAL BOUNDARIES
-----------------------------
- Preserves full provenance for every retrieved item (title, organization, year, verified URL, identifier).
- No fake citations, no automated web scraping, no fabricated URLs.
- Observational or guideline evidence is presented as population-level clinical background;
  it does NOT claim that an individual user has a disease or confirmed biological impairment.
- Operates deterministically without ML/vector model dependencies for predictable testability.
"""

import logging
from typing import Any, Optional
from pydantic import BaseModel, Field

from app.services.evidence_corpus import (
    EVIDENCE_CORPUS,
    DOCUMENT_MAP,
    EvidenceDocument,
    EvidenceChunk,
)
from app.services.evidence_taxonomy import get_tag_domain, ALL_CANONICAL_TAGS
from app.services.context_engine import HealthContext

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Output Pydantic Models for Retrieved Evidence
# ---------------------------------------------------------------------------

class EvidenceItem(BaseModel):
    """A single retrieved, provenance-backed evidence excerpt."""
    evidence_id: str = Field(..., description="Unique identifier of the chunk or document.")
    document_id: str = Field(..., description="Parent guideline/study identifier.")
    chunk_id: Optional[str] = Field(None, description="Specific chunk identifier if applicable.")
    title: str = Field(..., description="Official title of the clinical guideline or review.")
    source: str = Field(..., description="Short source citation (e.g. WHO, AUA/ASRM, EAU).")
    organization: str = Field(..., description="Publishing medical association or journal.")
    publication_year: Optional[int] = Field(None, description="Year of publication.")
    document_type: str = Field(..., description="'guideline', 'systematic_review', or 'consensus'.")
    url: str = Field(..., description="Verified, official URL to the publication.")
    source_identifier: str = Field(..., description="Official DOI, PMID, or ISBN.")
    matched_tags: list[str] = Field(default_factory=list, description="Evidence tags from query that matched this item.")
    relevance_reason: str = Field(..., description="Explainable reason why this guideline excerpt was retrieved.")
    excerpt: str = Field(..., description="Concise, factual summary of the guideline recommendation or evidence.")
    limitations: list[str] = Field(default_factory=list, description="Documented clinical and methodology limitations.")


class EvidenceContext(BaseModel):
    """Consolidated evidence context container returned by the retrieval service."""
    query_tags: list[str] = Field(default_factory=list, description="Input evidence tags queried.")
    matched_count: int = Field(0, description="Total number of evidence items retrieved.")
    items: list[EvidenceItem] = Field(default_factory=list, description="Ranked, deduplicated evidence items.")
    domain_distribution: dict[str, int] = Field(default_factory=dict, description="Count of matched items per health domain.")
    limitations_summary: list[str] = Field(default_factory=list, description="Aggregated limitations across all retrieved sources.")


# ---------------------------------------------------------------------------
# Core Retrieval Function
# ---------------------------------------------------------------------------

def retrieve_evidence(
    evidence_tags: Optional[list[str]],
    query_context: Optional[dict[str, Any]] = None,
    top_k: int = 5,
) -> EvidenceContext:
    """
    Retrieve authoritative clinical evidence items matching the given evidence tags.

    Parameters
    ----------
    evidence_tags : list[str] or None
        List of canonical evidence tag strings generated by the Context Engine.
    query_context : dict, optional
        Optional additional context (e.g. specific domain filter).
    top_k : int, default 5
        Maximum number of distinct evidence items to return.

    Returns
    -------
    EvidenceContext
        Structured Pydantic model with ranked, provenance-preserving evidence items.
    """
    if not evidence_tags:
        return EvidenceContext(
            query_tags=[],
            matched_count=0,
            items=[],
            domain_distribution={},
            limitations_summary=[],
        )

    # 1. Clean and deduplicate query tags
    clean_query_tags = sorted(list({t.strip().lower() for t in evidence_tags if isinstance(t, str) and t.strip()}))
    if not clean_query_tags:
        return EvidenceContext(
            query_tags=[],
            matched_count=0,
            items=[],
            domain_distribution={},
            limitations_summary=[],
        )

    query_tag_set = set(clean_query_tags)
    scored_candidates: list[tuple[float, EvidenceItem]] = []

    # 2. Match against all chunks in the authoritative corpus
    for doc in EVIDENCE_CORPUS:
        for chunk in doc.chunks:
            chunk_tag_set = {t.lower() for t in chunk.evidence_tags}
            matched = sorted(list(query_tag_set.intersection(chunk_tag_set)))

            if not matched:
                # Fallback: check if parent document tags match
                doc_tag_set = {t.lower() for t in doc.evidence_tags}
                doc_matched = sorted(list(query_tag_set.intersection(doc_tag_set)))
                if not doc_matched:
                    continue
                matched = doc_matched

            # Calculate deterministic relevance score:
            # - Base score from number of matched tags
            # - Bonus for official guidelines over reviews
            # - Recency bonus (year)
            # - Tie breaker is deterministic by doc.id and chunk.chunk_id
            type_weight = 5.0 if doc.document_type == "guideline" else 3.0
            recency_weight = (doc.publication_year - 2000) * 0.05
            score = (len(matched) * 10.0) + type_weight + recency_weight

            relevance_reason = f"Matched {len(matched)} evidence tag(s) ({', '.join(matched[:3])}) from {doc.source} ({doc.publication_year})."
            
            combined_limitations = list(dict.fromkeys(chunk.limitations + doc.limitations))

            item = EvidenceItem(
                evidence_id=chunk.chunk_id,
                document_id=doc.id,
                chunk_id=chunk.chunk_id,
                title=doc.title,
                source=doc.source,
                organization=doc.organization,
                publication_year=doc.publication_year,
                document_type=doc.document_type,
                url=doc.url,
                source_identifier=doc.source_identifier,
                matched_tags=matched,
                relevance_reason=relevance_reason,
                excerpt=chunk.text,
                limitations=combined_limitations,
            )
            scored_candidates.append((score, item))

    # 3. Deterministic Sort: by (-score, -publication_year, document_id, chunk_id)
    scored_candidates.sort(
        key=lambda x: (-x[0], -(x[1].publication_year or 0), x[1].document_id, x[1].chunk_id or "")
    )

    # 4. Deduplicate: keep highest scoring chunk per document/topic
    seen_chunks: set[str] = set()
    deduped_items: list[EvidenceItem] = []

    for _, item in scored_candidates:
        if item.evidence_id in seen_chunks:
            continue
        seen_chunks.add(item.evidence_id)
        deduped_items.append(item)
        if len(deduped_items) >= top_k:
            break

    # 5. Compute domain distribution & aggregate unique limitations
    domain_dist: dict[str, int] = {}
    aggregated_limitations: list[str] = []

    for item in deduped_items:
        for tag in item.matched_tags:
            dom = get_tag_domain(tag) or "general"
            domain_dist[dom] = domain_dist.get(dom, 0) + 1
        for lim in item.limitations:
            if lim not in aggregated_limitations:
                aggregated_limitations.append(lim)

    logger.debug(
        "Evidence retrieval completed. Query tags: %d, Matched items: %d (top_k=%d).",
        len(clean_query_tags),
        len(deduped_items),
        top_k,
    )

    return EvidenceContext(
        query_tags=clean_query_tags,
        matched_count=len(deduped_items),
        items=deduped_items,
        domain_distribution=domain_dist,
        limitations_summary=aggregated_limitations,
    )


# ---------------------------------------------------------------------------
# Context Engine Integration Helper
# ---------------------------------------------------------------------------

def retrieve_evidence_for_health_context(
    health_context: HealthContext,
    top_k: int = 6,
) -> EvidenceContext:
    """
    Extracts all evidence_tags from a HealthContext object and retrieves matching guidelines.

    Parameters
    ----------
    health_context : HealthContext
        The structured health context produced by `build_health_context()`.
    top_k : int, default 6
        Maximum number of distinct evidence items to return.

    Returns
    -------
    EvidenceContext
        Structured container of matching clinical guidelines with complete provenance.
    """
    if not isinstance(health_context, HealthContext):
        return EvidenceContext()

    all_tags: set[str] = set()

    # Collect tags from factors
    for factor in health_context.modifiable_factors:
        all_tags.update(factor.evidence_tags)
    for factor in health_context.positive_factors:
        all_tags.update(factor.evidence_tags)
    for factor in health_context.context_flags:
        all_tags.update(factor.evidence_tags)
    for factor in health_context.follow_up_flags:
        all_tags.update(factor.evidence_tags)

    # Collect tags from domain context summaries
    all_tags.update(health_context.domains.reproductive_health.evidence_tags)
    all_tags.update(health_context.domains.sexual_health.evidence_tags)
    all_tags.update(health_context.domains.lifestyle_wellness.evidence_tags)
    all_tags.update(health_context.domains.environmental_heat.evidence_tags)
    all_tags.update(health_context.domains.mental_behavioral_wellness.evidence_tags)
    all_tags.update(health_context.domains.substance_medication.evidence_tags)

    sorted_tags = sorted(list(all_tags))
    return retrieve_evidence(sorted_tags, top_k=top_k)
